In [1]:
import pandas as pd
import numpy as np
import statsmodels.formula.api as smf
import statsmodels.api as sm

In [7]:
nssal2000 = pd.read_stata("CaseStudyNSSAL/UKDA-5223-stata/NSSAL_2000.dta") 
nssal2000.head()

,sserial,psu,final_wt,strata,stdreg,gor,gor2,dateyoi,dage,rsex,...,r1datel,r1datef4,r1datef3,r1datef2,r1datef,hhchildn,sample,totalstr,totalpsu,total_wt
0,3141302,1.0,1.085620,26.0,north,north west (incl. the old 'merseyside' region),england,1999,29,male,...,3,Not applicable,26,10,16,0,core sample,rest of britain,1,1.177823
1,3141252,1.0,0.545033,110.0,north,north west (incl. the old 'merseyside' region),england,1999,30,female,...,75,Not applicable,Not applicable as had <3 partners in last 5 years,Not applicable as had <2 partners in last 5 years,84,0,core sample,rest of britain,1,0.591327
2,3141372,1.0,0.515038,122.0,north,north west (incl. the old 'merseyside' region),england,1999,36,female,...,36,Not applicable,Not applicable as had <3 partners in last 5 years,Not applicable as had <2 partners in last 5 years,Not answered/can't remember date,1,core sample,rest of britain,1,0.558784
3,3141572,1.0,0.481492,134.0,north,north west (incl. the old 'merseyside' region),england,1999,41,female,...,5,Not applicable,Not applicable as had <3 partners in last 5 years,Not applicable as had <2 partners in last 5 years,217,0,core sample,rest of britain,1,0.522389
4,3141382,1.0,0.481492,134.0,north,north west (incl. the old 'merseyside' region),england,1999,43,female,...,Not applicable,Not applicable,Not applicable as had <3 partners in last 5 years,Not applicable as had <2 partners in last 5 years,Not applicable,0,core sample,rest of britain,1,0.522389

In [8]:
nssal2010 = pd.read_stata("CaseStudyNSSAL/UKDA-7799-stata/NSSAL_2010.dta")
nssal2010.head()

,sin2,dateyoi,total_wt,psu_scrm,strata,stratagrp,stratagrp2,stratagrp3,dage,dagegr,...,london,npopdens,snpopdens,wnpopdens,adj_imd_quintile,qimd,qwimd,qsimd,urindew,urindsc
0,9110103,2010,0.460514,1636,763,332,221,166,25,25-34,...,Elsewhere,Not applicable,Not applicable,(17.546 - 115.396) most dense,3,Not applicable,9.70->14.79,Not applicable,Urban >= 10k - less sparse,not in Scotland
1,9110105,2010,1.788954,1636,763,332,221,166,30,25-34,...,Elsewhere,Not applicable,Not applicable,(17.546 - 115.396) most dense,4,Not applicable,21.42->33.03,Not applicable,Urban >= 10k - less sparse,not in Scotland
2,9110109,2010,1.381543,1636,763,332,221,166,29,25-34,...,Elsewhere,Not applicable,Not applicable,(17.546 - 115.396) most dense,3,Not applicable,9.70->14.79,Not applicable,Urban >= 10k - less sparse,not in Scotland
3,9110110,2010,0.739011,1636,763,332,221,166,27,25-34,...,Elsewhere,Not applicable,Not applicable,(17.546 - 115.396) most dense,4,Not applicable,21.42->33.03,Not applicable,Urban >= 10k - less sparse,not in Scotland
4,9110112,2010,1.923944,1636,763,332,221,166,41,35-44,...,Elsewhere,Not applicable,Not applicable,(17.546 - 115.396) most dense,3,Not applicable,9.70->14.79,Not applicable,Urban >= 10k - less sparse,not in Scotland

In [9]:
# Show all column names
print(nssal2000.columns.tolist())

['sserial', 'psu', 'final_wt', 'strata', 'stdreg', 'gor', 'gor2', 'dateyoi', 'dage', 'rsex', 'health', 'disabil', 'limit', 'illoracc', 'outpatyr', 'daypat', 'inpat', 'antenat', 'antenno', 'anbld', 'anwhn', 'drink', 'drinkany', 'drinkoft', 'manyalc', 'smokenow', 'nosmoke', 'exsmoke', 'kgweight', 'surewgt', 'pregnow', 'cmheight', 'anysibs', 'nosibs', 'sibspos', 'stepsibs', 'bothmapa', 'ynotboth', 'maorpa', 'anychild', 'nochild', 'samemf', 'adopchil', 'stepchil', 'talkmapa', 'learns01', 'learns02', 'learns03', 'learns04', 'learns05', 'learns06', 'learns07', 'learns08', 'learns09', 'learns10', 'learns11', 'learns12', 'lernsex1', 'lernsex2', 'lernsex3', 'lernmost', 'mlernm01', 'mlernm02', 'mlernm03', 'mlernm04', 'mlernm05', 'mlernm06', 'learnm01', 'learnm02', 'learnm03', 'learnm04', 'learnm05', 'learnm06', 'learnm07', 'learnm08', 'learnm09', 'learnm10', 'learnm11', 'wholern1', 'wholern2', 'wholernx', 'firstint', 'xfrstint', 'firstexp', 'xfrstexp', 'nextint', 'nextage', 'xnxtage', 'privacy', 'feaccept', 'whyfecd', 'fecomp', 'age1part', 'xage1prt', 'parts1st', 'bothwill', 'prtwill', 'anyprec1', 'anyprec2', 'anyprec3', 'anyprec4', 'anyprec5', 'justmet', 'rttime', 'mainreas', 'mmainre1', 'mmainre2', 'mmainre3', 'mmainre4', 'mmainre5', 'mmainre6', 'mmainre7', 'mmainre8', 'mmainre9', 'everus01', 'everus02', 'everus03', 'everus04', 'everus05', 'everus06', 'everus07', 'everus08', 'everus09', 'everus10', 'everus11', 'everus12', 'everus13', 'everusd1', 'everusd2', 'usedye01', 'usedye02', 'usedye03', 'usedye04', 'usedye05', 'usedye06', 'usedye07', 'usedye08', 'usualco1', 'usualco2', 'usualco3', 'whycond', 'ifboth', 'fpsour01', 'fpsour02', 'fpsour03', 'fpsour04', 'fpsour05', 'fpsour06', 'fpsour07', 'fpsour08', 'fpsrcex1', 'fpsrcex2', 'fppref', 'attscale', 'expscale', 'scaccept', 'xscace01', 'xscace02', 'xscace03', 'xscace04', 'xscacpt1', 'xscacpt2', 'xscacpt3', 'offpapi', 'sex4wks1', 'sex4wks2', 'hetsc', 'est4wks', 'no4wks', 'n1in4wk', 'new4wks', 'cond4wk', 'sex7day', 'lastvag', 'oralyou', 'oralprt', 'analsex', 'gencont', 'yrcond', 'nonocon', 'masturb', 'everhom', 'frsthom', 'genihom', 'ageghom', 'nextageg', 'hom4wks', 'homes4w', 'homno4w', 'h1new4w', 'homnw4w', 'homco4w', 'hom7day', 'homoyou', 'homopar', 'homayou', 'homahim', 'homgen', 'ancom', 'noancom', 'gaypub', 'hetlife', 'hetsure', 'het5yrs', 'het1yr', 'nonewpt', 'hetnewp', 'het3mnt', 'homlife', 'homsure', 'hom5yrs', 'hom1yr', 'homnewp', 'hnonewp', 'hom3mnt', 'travel', 'trvlsex', 'nosextl', 'cntry101', 'cntry102', 'cntry103', 'cntry104', 'cntry105', 'cntry106', 'cntry107', 'cntry108', 'cntry109', 'cntry110', 'cntry1x1', 'cntry1x2', 'sexabrd', 'nosexab', 'cntry201', 'cntry202', 'cntry203', 'cntry204', 'cntry205', 'cntry206', 'cntry207', 'cntry208', 'cntry2x1', 'r1sex', 'r1condl', 'r1first', 'r1condf', 'r1ptage', 'r1relat', 'r1meet', 'r1live', 'r1known', 'r1sex2', 'r1condl2', 'r1first2', 'r1condf2', 'r1ptage2', 'r1relat2', 'r1meet2', 'r1live2', 'r1known2', 'r1sex3', 'r1condl3', 'r1first3', 'r1condf3', 'r1ptage3', 'r1relat3', 'r1meet3', 'r1live3', 'r1known3', 'r1sex4', 'r1condl4', 'r1first4', 'r1condf4', 'r1ptage4', 'r1relat4', 'r1meet4', 'r1live4', 'r1known4', 'everpd', 'lastpay', 'nopaid', 'payprev', 'hompaid', 'homplst', 'hompdno', 'hompdp', 'miscarr', 'whnmisc', 'abort', 'manyab', 'ageab', 'ageabfir', 'ageablas', 'infertl', 'medhelp', 'stdclin', 'whnclin', 'diagnos1', 'diagnos2', 'diagnos3', 'diagnos4', 'diagnos5', 'diagnos6', 'diagnos7', 'whndiag1', 'whndiag2', 'whndiag3', 'whndiag4', 'whndiag5', 'whndiag6', 'whndiag7', 'whndiag8', 'diagno2', 'diagno3', 'diagno4', 'diagno5', 'diagwhe2', 'diagwhe3', 'diagwhe4', 'diagwhe5', 'inject', 'prescrb', 'medcond1', 'medcond2', 'medcond3', 'wheninj', 'needle', 'donblod', 'whendon', 'hivtsty', 'hivtstn', 'whytest1', 'whytest2', 'whytest3', 'whytest4', 'whytest5', 'whentest', 'whertest', 'restest', 'circum2', 'periods2', 'resultsc', 'circum1', 'periods1', 'impfaith', 'impinc', 'impresp', 'imprelig', 'impsexre', 'impshare', 'impchild', 'imptaste', 'rwpremar', 'rwadult', 'rwcohab', 'rwregp', 'rwcasual', 'rwhomm', 'rwhomf', 'rwabort', 'agaffec', 'agorgasm', 'agorgasf', 'agseximp', 'frequent', 'satisfy', 'easyyou', 'idealnow', 'ideal5yr', 'anychang', 'howchan1', 'howchan2', 'howchan3', 'howchan4', 'howchan5', 'howchan6', 'howchan7', 'rskyou', 'rskprom', 'rskmarr', 'rskmocc', 'rskhomm', 'rskhomf', 'rskdrugs', 'cfgbusa', 'cfgbswi', 'cfgbken', 'cfgbneth', 'cfgbthai', 'marstat', 'hhsize', 'tenure', 'livehere', 'whenmove', 'bornin', 'ebornin', 'agebrit', 'ractiv01', 'ractiv02', 'ractiv03', 'ractiv04', 'ractivx1', 'ractivx2', 'ractivx3', 'ractivhi', 'hours', 'rlastjob', 'revraway', 'rngtaway', 'rempstat', 'rdirctr', 'rmanage', 'rempnum', 'rsenum', 'rsoc_1', 'rseg', 'rsc', 'rsic', 'cie', 'pactiv01', 'pactiv02', 'pactiv03', 'pactivx1', 'pactivx2', 'phours', 'pactivhi', 'plastjob', 'pevraway', 'pngtaway', 'pempstat', 'pdirctr', 'pmanage', 'pempnum', 'psenum', 'psoc_1', 'pseg', 'psc', 'psic', 'tedage', 'anyexam', 'exams', 'anyqual', 'quals01', 'quals02', 'quals03', 'quals04', 'quals05', 'quals06', 'quals07', 'quals08', 'quals09', 'quals10', 'quals11', 'qualsx1', 'qualsx2', 'qualsx3', 'qualyr', 'typesch', 'boarder', 'par1occ', 'par2occ', 'par3occ', 'parsc', 'religimp', 'belrelig', 'whirel', 'oftrelig', 'urefcode', 'urinsamp', 'ct_lab', 'c_result', 'urine_wt', 'others', 'whothere', 'd63', 'd64', 'd65', 'd66', 'd67', 'd68', 'scseen', 'langprob', 'litprob', 'cogprob', 'readcard', 'embarras', 'difficlt', 'willing', 'areatype', 'bldtype', 'typdwell', 'ethmix', 'imdgbq', 'onsshort', 'agrp', 'agrp2', 'smoking', 'msedmum', 'mseddad', 'msedbro', 'msedsis', 'msedrel', 'msedsch', 'msedfrn', 'msedfsp', 'mseddoc', 'msedtv', 'msedvid', 'msedbks', 'msedmag', 'msedoth', 'sexedmum', 'sexeddad', 'sexedbro', 'sexedsis', 'sexedrel', 'sexedsch', 'sexedfrn', 'sexedfsp', 'sexeddoc', 'sexedtv', 'sexedvid', 'sexedbks', 'sexedmag', 'sexedoth', 'sexedsrc', 'sexedsr2', 'adeqinfo', 'knowgbd', 'knowbbd', 'knowborn', 'knowsex', 'knowfp', 'knowhom', 'knowmast', 'knowsati', 'knowno', 'knowfeel', 'knowstd', 'mumadfp', 'dadadfp', 'brotadfp', 'sistadfp', 'reladfp', 'schadfp', 'frieadfp', 'firpadfp', 'docadfp', 'tvadfp', 'vidadfp', 'bookadfp', 'magsadfp', 'othadfp', 'lernmorg', 'wholerng', 'notalk', 'afsex', 'gafsex', 'afsexgp', 'afsexall', 'hetb416', 'hetb416a', 'afexp', 'fscondom', 'fspill', 'fsother', 'fswithdw', 'fsrhythm', 'fspartdk', 'fsneithr', 'fscantre', 'justmet2', 'curious', 'feelings', 'peers', 'followon', 'drunk', 'losevirg', 'inlove', 'othrfact', 'pleasprt', 'raped', 'minipill', 'combpill', 'dkpill', 'mirena', 'coil', 'condom', 'femidom', 'cap', 'gels', 'sponge', 'persona', 'rhythm', 'withdraw', 'injectns', 'implants', 'emergncy', 'fsterils', 'msterils', 'abstain', 'otherfp', 'notused', 'conpill', 'yminipil', 'ycompill', 'ydkpill', 'ymirena', 'ycoil', 'ycondom', 'yfemidom', 'ycap', 'ygels', 'ysponge', 'ypersona', 'yrhythm', 'ywithdrw', 'yinjectn', 'yimplant', 'yemergcy', 'yfsteril', 'ymsteril', 'yabstain', 'yothrfp', 'yconpill', 'ynotused', 'dblcon', 'uminipil', 'ucompill', 'udkpill', 'umirena', 'ucoil', 'ucondom', 'ufemidom', 'ucap', 'ugels', 'usponge', 'upersona', 'urhythm', 'uwithdrw', 'uinjectn', 'uimplant', 'uemergcy', 'ufsteril', 'umsteril', 'uabstain', 'uother', 'unone', 'uconpill', 'condreas', 'owngp', 'anothrgp', 'anygp', 'surgfpcl', 'lhafpcl', 'youngcl', 'chemist', 'othrshop', 'vendmach', 'thrupost', 'aehosptl', 'othrserv', 'nonthese', 'het', 'hom', 'scelig', 'hettot', 'het5yrg', 'het1yrg', 'het3mntg', 'homever', 'homtot', 'homlst5y', 'hom5yrg', 'homlst1y', 'hom1yrg', 'hom3mntg', 'homnew4w', 'homnonew', 'homnew2', 'homnew3', 'totlife', 'tottot', 'tot5yrs', 'tot5yrg', 'tot5yrg2', 'tot1yr', 'tot1yrg', 'nosextl2', 'uk1', 'othereu1', 'oznz1', 'northam1', 'southam1', 'caribbn1', 'asia1', 'mideast1', 'ssafrca1', 'othercs1', 'sexabsum', 'nosexab2', 'othereu2', 'oznz2', 'northam2', 'southam2', 'caribbn2', 'asia2', 'mideast2', 'ssafrca2', 'othercs2', 'dkcrcs2', 'forsexsp', 'whnclin2', 'whncl5yr', 'attendcl', 'dkstd', 'herpes', 'trich', 'gonorrh', 'syphilis', 'chlamyda', 'nsungu', 'warts', 'pid', 'thrush', 'eversti', 'eversti2', 'eversti3', 'evervirl', 'everbact', 'yrsherpe', 'whnherpe', 'yrstrich', 'whntrich', 'yrsgonor', 'whngonor', 'yrssyphl', 'whnsyphl', 'yrschlam', 'whnchlam', 'yrsnsung', 'whnnsung', 'yrswarts', 'whnwarts', 'yrspid', 'whnpid', 'nostis', 'no_trich', 'no_gonor', 'no_syph', 'no_chlam', 'diabetes', 'allergy', 'chrnpain', 'thrombos', 'infectns', 'psychiat', 'addictn', 'othconds', 'drugs', 'inject5y', 'inject1y', 'hivtest', 'whntest2', 'hivtest5', 'hivtstly', 'testpreg', 'testinsr', 'testhchk', 'testrisk', 'testothr', 'testoth2', 'lackint', 'anxiety', 'orgasmno', 'preorgsm', 'painsic', 'erection', 'lubricat', 'noofprob', 'spgp', 'spstdcl', 'sppsych', 'spmarrc', 'spothrgp', 'sphelpl', 'spelse', 'spnone', 'circum', 'periods', 'periodgp', 'rrsfewrp', 'rrsknosh', 'rrscondm', 'rrsabstn', 'rrsmonog', 'rrsavoid', 'rrsother', 'ms', 'ms2', 'ms3', 'religion', 'religio2', 'ethnic11', 'bornin_g', 'concurt1', 'concurt2', 'concurt', 'l5ypartn', 'concrtly', 'lypartn', 'lypartn2', 'unitspw', 'alcohol', 'bodymass', 'bmigroup', 'usecondm', 'useco_gp', 'prts4wks', 'page', 'pplive', 'ppnum', 'ppms', 'ppmar', 'ppsex', 'ppwhy01', 'ppwhy02', 'ppwhy03', 'ppwhy04', 'ppwhy05', 'ppwhy06', 'ppwhy07', 'ppwhy08', 'ppwhy09', 'ppwhy10', 'ppwhy11', 'ppwhyx1', 'ppwhyx2', 'ppwhyx3', 'ppms2', 'ppmar2', 'ppsex2', 'ppwhy14', 'ppwhy15', 'ppwhy16', 'ppwhy17', 'ppwhy18', 'ppwhy19', 'ppwhy20', 'ppwhy21', 'ppwhy22', 'ppwhy23', 'ppwhyx4', 'ppwhyx5', 'ppms3', 'ppmar3', 'ppsex3', 'ppwhy27', 'ppwhy28', 'ppwhy29', 'ppwhy30', 'ppwhy31', 'ppwhy32', 'ppwhy33', 'ppwhy34', 'ppwhy35', 'ppwhyx7', 'ppwhyx8', 'ppms4', 'ppmar4', 'ppsex4', 'ppwhy40', 'ppwhy41', 'ppwhy42', 'ppwhy43', 'ppwhy44', 'ppwhy45', 'ppwhy46', 'ppwhy47', 'ppwhyx10', 'ppwhyx11', 'ppms5', 'ppmar5', 'ppsex5', 'ppwhy53', 'ppwhy54', 'ppwhy55', 'ppwhy56', 'ppwhy57', 'ppwhy58', 'ppwhy59', 'ppwhy60', 'ppwhyx13', 'ppms6', 'ppmar6', 'ppsex6', 'ppwhy66', 'ppwhy67', 'ppwhy68', 'ppwhy69', 'ppwhy70', 'ppwhyx16', 'ppwhyx17', 'ppwhyx18', 'ppms7', 'ppmar7', 'ppsex7', 'ppwhy79', 'ppwhy80', 'ppwhy81', 'ppwhyx19', 'ppwhyx20', 'ppwhyx21', 'ppms8', 'ppmar8', 'ppsex8', 'ppwhy92', 'ppwhy93', 'ppwhy94', 'ppwhy95', 'ppwhyx22', 'ppwhyx23', 'ppwhyx24', 'ppms9', 'ppmar9', 'ppsex9', 'ppwhy105', 'ppwhyx25', 'ppwhyx26', 'ppwhyx27', 'ppms10', 'ppmar10', 'ppsex10', 'ppwhy118', 'ppms11', 'ppmar11', 'ppsex11', 'ppms12', 'ppmar12', 'ppsex12', 'ppwhy144', 'usex', 'usex2', 'hetnonew', 'hetnew2', 'hetnew3', 'totnewyr', 'totnewy2', 'totnewy3', 'london', 'agefsp', 'orl2hevr', 'orl2hl5y', 'orl2hyr', 'orl2hlm', 'orlfhevr', 'orlfhl5y', 'orlfhyr', 'orlfhlm', 'anyorevr', 'anyorl5y', 'anyoraly', 'anyoralm', 'analhevr', 'analh5yr', 'analhyr', 'analhlm', 'mastbevr', 'mastbl5y', 'mastbyr', 'mastblm', 'vagsxevr', 'vagsxl5y', 'vagsexyr', 'vagsexlm', 'genhevr', 'genhl5y', 'genhlyr', 'genhlm', 'parsc2', 'parsc_kw', 'exams2', 'educ', 'educ2', 'educ3', 'singlsex', 'evrpdany', 'paid5yrs', 'paid1yr', 'anlhmevr', 'anlhml5y', 'anlhmlyr', 'anlhmlm', 'sexcomp', 'afhom13', 'nonocong', 'yrcond2', 'nocondom', 'nocondmg', 'parents', 'parents2', 'fpsourcg', 'age1chil', 'occs4wk1', 'occs4wk2', 'occs4wkg', 'tv_l5y', 'gc_l5y', 'syph_l5y', 'ct_l5y', 'nsu_l5y', 'pid_l5y', 'bact_l5y', 'hsv_l5y', 'wart_l5y', 'virl_l5y', 'any_l5y', 'prtwill2', 'rafsmr', 'rafs2mr', 'rafs3mr', 'ifdysf', 'whdysf1', 'whdysf2', 'whdysf3', 'whdysf4', 'whdysf5', 'whdysf6', 'longdys1', 'longdys2', 'longdys3', 'longdys4', 'longdys5', 'longdys6', 'longdys7', 'avoisex', 'contact1', 'contact2', 'contact3', 'contact4', 'ifcon1', 'ifcon2', 'ifcon3', 'ifcon4', 'ifcon5', 'age1cohb', 'cohab420', 'langi01', 'langi02', 'langi03', 'langi04', 'langi05', 'langi06', 'clangi1', 'clangi2', 'clangi3', 'langm', 'intlang', 'ilangwh', 'rsc_gp2', 'rsc_kw', 'psc_gp2', 'sc', 'fsprecgp', 'fsprecg2', 'whnmisc2', 'mcsbl5y', 'ageaball', 'ageabal2', 'abort18', 'abort20', 'abortl5y', 'abortlyr', 'tenure2', 'tv_lyr', 'gc_lyr', 'syph_lyr', 'ct_lyr', 'nsu_lyr', 'pid_lyr', 'bact_lyr', 'hsv_lyr', 'wart_lyr', 'virl_lyr', 'any_lyr', 'longdysg', 'longdy1g', 'longdy2g', 'longdy3g', 'longdy4g', 'longdy5g', 'longdy6g', 'longdy7g', 'noofpro2', 'r1datel4', 'r1datel3', 'r1datel2', 'r1datel', 'r1datef4', 'r1datef3', 'r1datef2', 'r1datef', 'hhchildn', 'sample', 'totalstr', 'totalpsu', 'total_wt']

In [10]:
print(nssal2010.columns.tolist())

['sin2', 'dateyoi', 'total_wt', 'psu_scrm', 'strata', 'stratagrp', 'stratagrp2', 'stratagrp3', 'dage', 'dagegr', 'agrp', 'agrp2', 'rdoby', 'birthcohort', 'rsex', 'health', 'disabil', 'limit', 'disabil2', 'medcona', 'medwcha1', 'medwcha2', 'medwcha3', 'medwcha4', 'medwcha5', 'medwcha6', 'medwcha7', 'medwcha8', 'medwcha9', 'drgheart', 'drghyp', 'drgins', 'drgdi', 'drgpark', 'drgepil', 'medconb', 'medwchb1', 'medwchb2', 'medwchb3', 'medwchb4', 'medwchb5', 'medwchb6', 'medwchb7', 'medwchb8', 'drgpros', 'medconc', 'medwchc1', 'medwchc2', 'medwchc3', 'medwchc4', 'medwchc5', 'medwchc6', 'medwchc7', 'whnhystgpd', 'medcond', 'medwchd1', 'medwchd2', 'medwchd3', 'medwchd4', 'medwchd5', 'medwchd6', 'medwchd7', 'medwchd8', 'medwchd9', 'medwchd10', 'drgdep', 'drgmh', 'hefunc', 'heatt1', 'heatt2', 'heatt3', 'heatt4', 'heatt5', 'heatt6', 'heatt7', 'heatt8', 'heatt9', 'heatt10', 'heatt11', 'heatt12', 'drink', 'drinkoft', 'manyalc2', 'unitspw', 'alcohol2', 'alcohol3', 'alcoholn', 'drinknum', 'smokenow', 'nosmoke', 'exsmoke', 'smoking', 'smoker', 'kgweight', 'cmheight', 'bodymass', 'bmiwho', 'sibany1', 'sibany2', 'sibany3', 'sibany4', 'sibany5', 'sibany6', 'sibany7', 'sibany8', 'sibany9', 'sibbro', 'sibsis', 'sibadbr', 'sibadsis', 'sibhabr', 'sibhasis', 'sibstbr', 'sibstsis', 'siblive', 'sibpos2', 'bothmapa2', 'ynotboth2', 'wholive', 'parents3', 'parents4', 'talkmapa', 'notalk', 'sexedudoc', 'sexeduintad', 'sexedusch', 'sexeduinto', 'sexedubmn', 'sexedufrn', 'sexedutvid', 'sexedumum', 'sexedudad', 'sexedufsp', 'sexeduintpn', 'sexedupor', 'sexedubsis', 'sexeduoth', 'sexeduani', 'sexedurel', 'sexeduofri', 'sexeduofrn', 'sexeduexp', 'sexedufil', 'sexeduedc', 'lernmost', 'mseddoc', 'msedintad', 'msedsch', 'msedinto', 'msedbmn', 'msedfrn', 'msedtvid', 'msedmum', 'mseddad', 'msedfsp', 'msedintpn', 'msedpor', 'msedbsis', 'msedoth', 'msedani', 'msedrel', 'msedofri', 'msedofrn', 'msedexp', 'msedfil', 'msededc', 'sexedsrc', 'sexedsr2', 'knowosp', 'knowall', 'knowgbd', 'knowstd', 'knowsafe', 'knowsex', 'knowcond', 'knowsati', 'knowhom', 'knowfeel', 'knowbbd', 'knowfp', 'knowno', 'knowmast', 'knowborn', 'knownsure', 'knownone', 'knownsex', 'lernmorg', 'adeqinfo', 'docadfp', 'intadadfp', 'schadfp', 'intoadfp', 'bmnadfp', 'frieadfp', 'tvidadfp', 'mumadfp', 'dadadfp', 'fspadfp', 'intpnadfp', 'poradfp', 'bsisadfp', 'othadfp', 'reladfp', 'afsex', 'gafsex', 'afsexgp', 'afsexall', 'hetb416', 'hetb416a', 'afexp', 'zmodefexp', 'zage1part', 'zxage1prt', 'agefsp', 'zparts1st', 'zbothwill', 'zprtwill', 'partmwill', 'forcond', 'forpill', 'forecont', 'foroth', 'fornone', 'fsprecfgp', 'contrameth', 'contramethall', 'zforjmet', 'fscondom', 'fspill', 'fsecont', 'fsother', 'fswithdw', 'fsrhythm', 'fspartdk', 'fsneithr', 'fsprecnfgp', 'fsprecnfg2', 'zjustmet2', 'justmetn2', 'zfstmet', 'zrttime', 'fstcurious', 'fstfeel', 'fstpeers', 'fstfollow', 'fstdrunk', 'fstcann', 'fstodrgs', 'fstlvirg', 'fstlove', 'fstothf', 'fstcrem', 'zmainrea2', 'curious', 'feelings', 'peers', 'followon', 'drunk', 'smkcann', 'othdrg', 'losevirg', 'inlove', 'othrfact', 'cantrem', 'cantchoo', 'sexcomp2', 'notused', 'fsterils', 'msterils', 'conpill', 'condom', 'femidom', 'emcypill', 'emcyiud', 'coil', 'mirena', 'cap', 'injectns', 'gels', 'rhythm', 'withdraw', 'implants', 'otherfp', 'conpatch', 'emergncy', 'ynotused', 'yfsteril', 'ymsteril', 'yconpill', 'ycondom', 'yfemidom', 'yemcypill', 'yemcyiud', 'ycoil', 'ymirena', 'ycap', 'yinjectn', 'ygels', 'yrhythm', 'ywithdrw', 'yimplant', 'yothrfp', 'yconptch', 'yemergncy', 'dblcon2', 'usfsteril', 'usmsteril', 'usconpill', 'uscondom', 'usfemidom', 'usemcypill', 'usemcyiud', 'uscoil', 'usmirena', 'uscap', 'usinjectn', 'usgels', 'usrhythm', 'uswithdrw', 'usimplant', 'usother', 'usconptch', 'usnotused', 'uemergcy', 'whycon21', 'whycon22', 'whycon23', 'sownsurg', 'sgumcl', 'sfprhcl', 'snhsancmw', 'sprivdoc', 'syoungcl', 'schemist', 'swebsite', 'seduserv', 'sothrshop', 'svendmach', 'sthrupost', 'saehosptl', 'sothrserv', 'snotgotfp', 'sfriendfp', 'sparrelfp', 'sprtnerfp', 'fpsorcg', 'fppref2', 'periods2', 'periodgp', 'period13', 'periods3', 'perlst', 'menopause', 'hrtever', 'hrtstill', 'attscale', 'expscale', 'het', 'sam', 'scelign3', 'scelign2', 'scaccept', 'xsccomp', 'xsceyes', 'xscread', 'xscodisab', 'xscobject', 'xscconfid', 'xsclang', 'xscrtime', 'xscboth', 'xscoth', 'resultsc', 'scf2f1', 'scf2f2', 'scf2f3', 'scf2f4', 'scf2f5', 'scf2f6', 'scf2f7', 'askcasi', 'hetcheck', 'everhet', 'lastvag', 'oralyou', 'oralprt', 'analsex', 'gencont2', 'vagsxevr', 'vagsxl5y', 'vagsexyr', 'vagsexlm', 'orl2hevr', 'orl2hl5y', 'orl2hyr', 'orl2hlm', 'orlfhevr', 'orlfhl5y', 'orlfhyr', 'orlfhlm', 'anyorevr', 'anyorl5y', 'anyoraly', 'anyoralm', 'analhevr', 'analh5yr', 'analhyr', 'analhlm', 'genhevr', 'genhl5y', 'genhlyr', 'genhlm', 'sex4wks', 'sex4wks1', 'sex4wks2', 'sexfreq', 'no4wks', 'new4wks', 'cond4wk', 'sex7day', 'yrcond', 'yrcond2', 'nonocon', 'nonocong', 'masturb', 'mastbevr', 'mastbl5y', 'mastbyr', 'mastblm', 'mastnum', 'eversam', 'frstsam', 'genisam', 'agegsam', 'nextageg', 'nextasam', 'afsam13', 'afsam13a', 'totafsex', 'totafsexgp', 'samsex', 'samoyou', 'samopar', 'samayou', 'samahim', 'anlhmevr', 'anlhml5y', 'anlhmlyr', 'anlhmlm', 'samgen', 'sam4wks', 'occs4wk1', 'occs4wk2', 'occs4wkg', 'sex4xlm', 'anysex4wk', 'samno4w', 'prts4wks', 'h1new4w', 'samnw4w', 'samnew4w', 'samco4w', 'usecondm', 'useco_gp', 'sam7day', 'ancom', 'noancom', 'gaypub2', 'hetlife', 'hettot', 'hetcalc', 'het5yrs', 'het5yrg', 'het1yr', 'het1yrg', 'usex', 'totusex', 'nonewpt', 'hetnewp', 'hetnonew', 'hetnew2', 'hetnew3', 'introos', 'oralon', 'oralpre', 'h1yrtot', 'h1yrtot2', 'swing', 'het3mnt', 'het3mntg', 'samlife', 'samcalc', 'samtot', 'sam5yrs', 'sam5yrg', 'samlst5y', 'sam1yr', 'sam1yrg', 'samlst1y', 'snonewp', 'samnewp', 'samnonew', 'samnew2', 'samnew3', 'sam3mnt', 'sam3mntg', 'overlp5y', 'netsex', 'totlife', 'tottot', 'tot5yrs', 'tot5yrg', 'tot5yrg2', 'tot1yr', 'tot1yrg', 'totnewyr', 'totnewy2', 'totnewy3', 'nocondom', 'nocondmg', 'dfover1p1', 'dfover1p2', 'dfover1p3', 'dfover1p4', 'dfover5p1', 'dfover5p2', 'dfover5p3', 'dfover5p4', 'dlover1p1', 'dlover1p2', 'dlover1p3', 'dlover1p4', 'dlover5p1', 'dlover5p2', 'dlover5p3', 'dlover5p4', 'r1recm', 'r1sex', 'r1condl', 'r1rel', 'r1sexagn', 'r1first', 'r1firstm', 'r1mtha', 'r1mthb', 'r1condf', 'r1rel1s', 'r1ptage', 'r1ethni', 'r1ethbl', 'r1meet', 'r1live', 'r1known', 'mrpos', 'r1recm2', 'r1sex2', 'r1condl2', 'r1rel2', 'r1sexagn2', 'r1first2', 'r1firstm2', 'r1mtha2', 'r1mthb2', 'r1condf2', 'r1rel1s2', 'r1ptage2', 'r1ethni2', 'r1ethbl2', 'r1meet2', 'r1live2', 'r1known2', 'mrpos2', 'r1recm3', 'r1sex3', 'r1condl3', 'r1rel3', 'r1sexagn3', 'r1first3', 'r1firstm3', 'r1mtha3', 'r1mthb3', 'r1condf3', 'r1rel1s3', 'r1ptage3', 'r1ethni3', 'r1ethbl3', 'r1meet3', 'r1live3', 'r1known3', 'mrpos3', 'r1recm4', 'r1sex4', 'r1condl4', 'r1rel4', 'r1sexagn4', 'r1first4', 'r1firstm4', 'r1mtha4', 'r1mthb4', 'r1condf4', 'r1rel1s4', 'r1ptage4', 'r1ethni4', 'r1ethbl4', 'r1meet4', 'r1live4', 'r1known4', 'mrpos4', 'mrpolap', 'mrpconcl5y1', 'mrpconcl5y2', 'mrpconcl5y', 'l5ypartn', 'mrpconcly1', 'mrpconcly2', 'mrpconcly', 'lypartn', 'lypartn2', 'rafsmr', 'rafs2mr', 'rafs3mr', 'rafs4mr', 'r1pcon1', 'r1pcon2', 'r1pcon3', 'r1pcon4', 'ad_mrp', 'ad_2mrp', 'ad_3mrp', 'ad_4mrp', 'travel', 'trvlsex', 'nosextl', 'nosextl2', 'uk1', 'othereu1', 'oznz1', 'northam1', 'southam1', 'caribbn1', 'asia1', 'mideast1', 'othafrica1', 'othercs1', 'dkrctry1', 'sexabsum', 'sexabrd', 'nosexab', 'nosexab2', 'othereu2', 'oznz2', 'northam2', 'southam2', 'caribbn2', 'asia2', 'mideast2', 'othafrica2', 'othercs2', 'dkrctry2', 'forsexsp', 'viotry', 'viosuc', 'viotry2', 'viosuc2', 'viowhen', 'viowho', 'viotalk', 'viopol', 'everpd', 'lastpay', 'nopaid', 'payprev', 'sampaid', 'samplst', 'sampdno', 'sampdp', 'payabrd', 'pothereu', 'poznz', 'pnortham', 'psoutham', 'pcaribbn', 'pasia', 'pmideast', 'pothafrica', 'pothercs', 'pdkrctry', 'evrpdany', 'paid5yrs', 'paid1yr', 'everpreg', 'nopreg', 'pregomisc', 'prmiscagf', 'pregosb', 'pregoab', 'prabagf', 'manyab2gp', 'prabagl', 'abort18_2', 'abort20_2', 'abortl5', 'agfstpreg', 'pregob418', 'lastpreg', 'dtlastpry', 'antenat2', 'pregyr', 'pregyrkw', 'lmupscr', 'lmup1', 'lmup2', 'lmup3', 'lmup4', 'lmup5', 'lmupfolic', 'lmupsmok', 'lmupdrk', 'lmuphlth', 'lmupmad', 'lmupoact', 'lmupnone', 'lmupscore', 'planstat', 'unplanned', 'pregrisk', 'anychm', 'anychall', 'nochall', 'prevparity', 'dobcmy01', 'dobcmy02', 'dobcmy03', 'dobcmy04', 'dobcmy05', 'dobcmy06', 'dobcmy07', 'dobcmy08', 'dobcmy09', 'dobcmy10', 'dobcmy11', 'dobcmy12', 'age1ch', 'child18', 'child20', 'nochb435', 'samemfm', 'adopchld', 'stepchld', 'fertint', 'fertwhy', 'infrt1y', 'medhelp', 'stdtrt', 'stdclin', 'whnclin', 'attendcl', 'whnclin2', 'whncl5yr', 'chlamydia', 'gonorrh', 'warts', 'syphilis', 'trich', 'herpes', 'plicecrab', 'hepatitis', 'nsungu', 'epididy', 'pid', 'thrush', 'bacvagin', 'dkstd', 'nostd', 'eversti', 'eversti2', 'eversti3', 'whnchlam', 'chtstwh1', 'chtstwy1', 'chtrtlgr', 'chlmtest', 'cttestly', 'chltstwh', 'chltstwy', 'chlofref', 'whngono', 'whergono', 'whnwarts', 'wherwart', 'whnsyphl', 'whersyph', 'whntric', 'whertric', 'whnherp', 'wherherp', 'whnnsu', 'whernsu', 'ct5y', 'gc5y', 'warts5y', 'syphl5y', 'tric5y', 'herp5y', 'nsu5y', 'ct1y', 'gc1y', 'any_l5y2', 'warts1y', 'syphl1y', 'tric1y', 'herp1y', 'nsu1y', 'any_ly2', 'everpap', 'hpvever', 'hpvcomp', 'hpvofref', 'hpvwhere', 'mstipainuri', 'mstipassmor', 'mstigenwart', 'mstigenulc', 'mstipdisch', 'mstipaintest', 'mstinone', 'fstipainuri', 'fstipassmor', 'fstigenwart', 'fstigenulc', 'fstivdisch', 'fstiodour', 'fstivpainsex', 'fstibleedper', 'fstibleedsex', 'fstiabdopain', 'fstinone', 'anystisympm', 'anystisympf', 'anystisymp', 'donblod2', 'whendon2', 'hivtsty', 'hivtstn', 'hivtest', 'testpreg', 'testinsr', 'testschk', 'testhchk', 'testcond', 'testrisk', 'testdoc', 'testothr2', 'testoth2', 'whentest', 'whntest2', 'hivtest5', 'hivtstly', 'whertest', 'restest', 'sfscore', 'lowerfuncofall', 'hafsex', 'mafsex', 'lackint3m', 'lackenj3m', 'anxsex3m', 'painsex3m', 'nonarou3m', 'nolgorg3m', 'premorg3m', 'lubric3m', 'erect3m', 'nosfprb3m', 'oneplus3m', 'twoplus3m', 'sfprlng', 'sfprfrq', 'sfprbds', 'sfprlng2', 'sfprfrq2', 'sfprbds2', 'sfprlng3', 'sfprfrq3', 'sfprbds3', 'sfprlng4', 'sfprfrq4', 'sfprbds4', 'sfprlng5', 'sfprfrq5', 'sfprbds5', 'sfprlng6', 'sfprfrq6', 'sfprbds6', 'sfprlng7', 'sfprfrq7', 'sfprbds7', 'sfprlng8', 'sfprfrq8', 'sfprbds8', 'sfprlng9', 'sfprfrq9', 'sfprbds9', 'sfrint', 'sfrlikes', 'sfrpdf', 'sfrem', 'sfrint2', 'sfrlikes2', 'sfrpdf2', 'sfrem2', 'relsat', 'relsat2', 'sffsatis', 'sffdst', 'sffavoid', 'sffsatis2', 'sffdst2', 'sffavoid2', 'avoilackint', 'avoilackenj', 'avoianxsex', 'avoipainsex', 'avoinonarou', 'avoinolgorg', 'avoipremorg', 'avoilubric', 'avoierect', 'avoipartprb', 'avoinone', 'spfamfr', 'spinternet', 'spbookslea', 'spselfh', 'sphelpl', 'spgp', 'spgumsti', 'sppsych', 'sprelc', 'spothrgp', 'spnohelp', 'sphelp', 'frequent', 'easyoua', 'easyoub', 'easyou', 'medper', 'medpwhn', 'drcannabis', 'drampheta', 'drcocaine', 'drcrack', 'drecstasy', 'drnonihero', 'dracidlsd', 'drcrysmeth', 'dramylnit', 'drothnonpre', 'drnone', 'drcan12m', 'drcan4w', 'drg12m', 'drg4w', 'inject2', 'wheninj', 'inject1y', 'injagfst', 'needle', 'drugsever', 'drugsyr', 'drugsyr2', 'mood1', 'mood2', 'mscore', 'depscr', 'circum', 'rwadult', 'rwcasual', 'rwsamm', 'rwsamf', 'snnolov', 'snpres', 'snold', 'snsexdrv', 'snmedia', 'snearly', 'sngayadp', 'snlesadp', 'snsexed', 'Ch1625', 'talkch', 'uagesex', 'rskyou', 'stirisk', 'hhsize', 'spoushh', 'civpthh', 'coopphh', 'cosamhh', 'partnerhh', 'hhpartage', 'childl12', 'child1217', 'childm17', 'parenthh', 'othrelhh', 'nonrelhh', 'rhhold', 'marstat', 'ms', 'ms2', 'ms3', 'relstat', 'relstatgp', 'relstatgp2', 'pplive', 'ppnum', 'pp1ystrt', 'pp1ms', 'pp1mar', 'age1cohb', 'cohab420', 'pp1ymar', 'pp1sex', 'pp1ystop', 'pp1months', 'pp1why1', 'pp1why2', 'pp1why3', 'pp1why4', 'pp1why5', 'pp1why6', 'pp1why7', 'pp1why8', 'pp1why9', 'pp1why10', 'pp1why11', 'pp1why12', 'pp1why13', 'pp1why14', 'pp1why15', 'pp1why16', 'pp1why17', 'pp1why18', 'pp1why19', 'pp1why20', 'pp1why21', 'pp1why22', 'pp1why23', 'pp1why24', 'pp1why25', 'pp2ystrt', 'pp2ms', 'pp2mar', 'pp2ymar', 'pp2sex', 'pp2ystop', 'pp2months', 'pp2why1', 'pp2why2', 'pp2why3', 'pp2why4', 'pp2why5', 'pp2why6', 'pp2why7', 'pp2why8', 'pp2why9', 'pp2why10', 'pp2why11', 'pp2why12', 'pp2why13', 'pp2why14', 'pp2why15', 'pp2why16', 'pp2why17', 'pp2why18', 'pp2why19', 'pp2why20', 'pp2why21', 'pp2why22', 'pp2why23', 'pp2why24', 'pp3ystrt', 'pp3ms', 'pp3mar', 'pp3ymar', 'pp3sex', 'pp3ystop', 'pp3months', 'pp4ystrt', 'pp4ms', 'pp4mar', 'pp4sex', 'pp4ystop', 'pp4months', 'pp5ystrt', 'pp5ms', 'pp5mar', 'pp5sex', 'pp5ystop', 'pp5months', 'pp1strt_ind', 'pp2strt_ind', 'pp3strt_ind', 'pp4strt_ind', 'pp5strt_ind', 'tenure', 'livehere', 'whenmove', 'rfted', 'rjpdwork', 'rgovtr', 'rueunpaid', 'rwaitwork', 'ruelookn', 'rtempsick', 'rpermsick', 'rretired', 'rhome', 'rother', 'ractivhi2', 'ractivhi3', 'employed', 'hours', 'revraway', 'rngtawaygpd', 'rnights', 'rlastjob', 'rempstat', 'rnssecgp_6', 'rnssecgp_4', 'rsoc2000_9', 'rsoc2000_7', 'RSOC2000_4', 'rsoc2010_9', 'rsoc2010_7', 'rsoc2010_4', 'pfted', 'pjpdwork', 'pgovtr', 'pueunpaid', 'pwaitwork', 'puelookn', 'ptempsick', 'ppermsick', 'pretired', 'phome', 'pother', 'pactivhi2', 'pactivhi3', 'phours', 'pevraway', 'pngtawaygpd', 'plastjob', 'pempstat', 'pnssecgp_6', 'pnssecgp_4', 'psoc2010_9', 'psoc2010_7', 'psoc2010_4', 'psoc2000_9', 'psoc2000_7', 'psoc2000_4', 'hhnssecgp_6', 'hhnssecgp_4', 'income', 'tedage', 'anyexam', 'educ', 'educ2', 'exams', 'exams2', 'anyqual', 'educ3', 'educ4', 'typesch', 'singlsex', 'boarder', 'par1occ', 'par2occ', 'par3occ', 'parsc3', 'parsc_kw', 'ethnicgrp', 'sexid', 'religimp', 'belrelig', 'whirel', 'religion', 'religio2', 'oftrelig', 'netacc', 'intagain', 'email', 'outcome', 'others', 'whothere', 'homespart', 'homepars', 'home0to5', 'home6to15', 'home16to21', 'home22', 'scseen', 'langprob', 'litprob', 'cogprob', 'readcard', 'embarras', 'willing', 'adults', 'gor', 'gor2', 'gor_l', 'london', 'npopdens', 'snpopdens', 'wnpopdens', 'adj_imd_quintile', 'qimd', 'qwimd', 'qsimd', 'urindew', 'urindsc']

In [11]:
# 1. Clean column names 
nssal2000.columns = nssal2000.columns.str.strip().str.lower()
nssal2010.columns = nssal2010.columns.str.strip().str.lower()

In [12]:
# 2. Keep only important variables for NSSAL 2000
cols_2000 = [
    "sserial",
    "rsex",
    "dage",
    "agrp",
    "agrp2",
    "total_wt",
    "psu",
    "strata",
    "hetlife",
    "hettot",
    "het5yrs",
    "het5yrg",
    "het1yr",
    "het1yrg",
    "het3mnt",
    "het3mntg",
    "hetnewp",
    "hetnonew",
    "hetnew2",
    "hetnew3",
    "educ",
    "educ2",
    "educ3",
    "exams2",
    "marstat",
    "ms",
    "ms2",
    "ms3",
    "gor",
    "gor2",
    "london",
    "het",
    "hom",
    "scelig",
    "sexcomp"
]
cols_2000_existing = [c for c in cols_2000 if c in nssal2000.columns]
missing_2000 = [c for c in cols_2000 if c not in nssal2000.columns]

print("Missing in 2000:", missing_2000)

nssal2000_small = nssal2000[cols_2000_existing].copy()

Missing in 2000: []

In [13]:
# 3. Keep only important variables for NSSAL 2010
cols_2010 = [
    "sin2",
    "rsex",
    "dage",
    "agrp",
    "agrp2",
    "total_wt",
    "psu_scrm",
    "strata",
    "hetlife",
    "hettot",
    "het5yrs",
    "het5yrg",
    "het1yr",
    "het1yrg",
    "het3mnt",
    "het3mntg",
    "hetnewp",
    "hetnonew",
    "hetnew2",
    "hetnew3",
    "educ",
    "educ2",
    "educ3",
    "exams2",
    "marstat",
    "ms",
    "ms2",
    "ms3",
    "gor",
    "gor2",
    "london",
    "het",
    "sam",
    "scelign2",
    "sexcomp2"
]

cols_2010_existing = [c for c in cols_2010 if c in nssal2010.columns]
missing_2010 = [c for c in cols_2010 if c not in nssal2010.columns]

print("Missing in 2010:", missing_2010)

nssal2010_small = nssal2010[cols_2010_existing].copy()

Missing in 2010: []

In [14]:
# 4. Rename variables so both datasets match
nssal2000_small = nssal2000_small.rename(columns={
    "sserial": "id"
})

nssal2010_small = nssal2010_small.rename(columns={
    "sin2": "id",
    "psu_scrm": "psu",
    "sam": "hom",
    "scelign2": "scelig",
    "sexcomp2": "sexcomp"
})

In [15]:
# 5. Add survey wave
nssal2000_small["survey_wave"] = "1999_2001"
nssal2010_small["survey_wave"] = "2010_2012"

In [16]:
# 6. Combine both datasets
combined = pd.concat(
    [nssal2000_small, nssal2010_small],
    ignore_index=True,
    sort=False
)

combined.head()

,id,rsex,dage,agrp,agrp2,total_wt,psu,strata,hetlife,hettot,...,ms2,ms3,gor,gor2,london,het,hom,scelig,sexcomp,survey_wave
0,3141302,male,29,25-34,25-29,1.177823,1.0,26.0,9,5-9,...,single and never been married,single and never been married,north west (incl. the old 'merseyside' region),england,elsewhere,het. sex. intercourse aged 13+,no hom. sex. experience ever,eligible,competent,1999_2001
1,3141252,female,30,25-34,30-34,0.591327,1.0,110.0,2,2,...,"previously married (widowed, divorced, separated)","previously married (widowed, divorced, separated)",north west (incl. the old 'merseyside' region),england,elsewhere,het. sex. intercourse aged 13+,no hom. sex. experience ever,eligible,competent,1999_2001
2,3141372,female,36,35-44,35-39,0.558784,1.0,122.0,12,10+,...,"previously married (widowed, divorced, separated)","previously married (widowed, divorced, separated)",north west (incl. the old 'merseyside' region),england,elsewhere,het. sex. intercourse aged 13+,no hom. sex. experience ever,eligible,competent,1999_2001
3,3141572,female,41,35-44,40-44,0.522389,1.0,134.0,3,3-4,...,married & living with spouse,married & living with spouse,north west (incl. the old 'merseyside' region),england,elsewhere,het. sex. intercourse aged 13+,no hom. sex. experience ever,eligible,not competent,1999_2001
4,3141382,female,43,35-44,40-44,0.522389,1.0,134.0,15,10+,...,single and never been married,single and never been married,north west (incl. the old 'merseyside' region),england,elsewhere,het. sex. intercourse aged 13+,no hom. sex. experience ever,eligible,not competent,1999_2001

In [17]:
#7. Keep an even smaller final analysis dataset
analysis_cols = [
    "id",
    "survey_wave",
    "rsex",
    "dage",
    "agrp",
    "het1yr",
    "het1yrg",
    "het5yrs",
    "het5yrg",
    "hettot",
    "educ3",
    "ms2",
    "gor2",
    "total_wt",
    "psu",
    "strata"
]

analysis_cols_existing = [c for c in analysis_cols if c in combined.columns]

analysis_df = combined[analysis_cols_existing].copy()
analysis_df.head()

,id,survey_wave,rsex,dage,agrp,het1yr,het1yrg,het5yrs,het5yrg,hettot,educ3,ms2,gor2,total_wt,psu,strata
0,3141302,1999_2001,male,29,25-34,2,2,4,3-4,5-9,"higher education, <degree level but a-level/eq...",single and never been married,england,1.177823,1.0,26.0
1,3141252,1999_2001,female,30,25-34,0,0,1,1,2,"gcse, o-level or equivalent","previously married (widowed, divorced, separated)",england,0.591327,1.0,110.0
2,3141372,1999_2001,female,36,35-44,0,0,1,1,10+,"higher education, <degree level but a-level/eq...","previously married (widowed, divorced, separated)",england,0.558784,1.0,122.0
3,3141572,1999_2001,female,41,35-44,1,1,1,1,3-4,none,married & living with spouse,england,0.522389,1.0,134.0
4,3141382,1999_2001,female,43,35-44,0,0,0,0,10+,degree,single and never been married,england,0.522389,1.0,134.0

In [18]:
# 8. Recode missing values
missing_map = {
    "hettot": [-1, 9],
    "het5yrs": [-1, 9995, 9996, 9997, 9999],
    "het5yrg": [-1, 9],
    "het1yrg": [-1, 9],
    "educ3": [9],
    "ms2": [9],
    "rsex": [-1,-9, -8, -2]
}

for col, values in missing_map.items():
    if col in analysis_df.columns:
        analysis_df[col] = analysis_df[col].replace(values, np.nan)

In [19]:
analysis_df["het1yr_clean"] = analysis_df["het1yr"].replace({
    -1: np.nan,
    999: np.nan,
    "not answered": np.nan,
    "Not answered": np.nan,
    "not applicable": np.nan,
    "Not applicable": np.nan,

    # conservative lower-bound coding
    995: 1,
    996: 2,
    997: 3,
    "at least one": 1,
    "At least one": 1,
    "at least two": 2,
    "At least two": 2,
    "at least three": 3,
    "At least three": 3
})

analysis_df["het1yr_clean"] = pd.to_numeric(
    analysis_df["het1yr_clean"],
    errors="coerce"
)

C:\Users\User\AppData\Local\Temp\ipykernel_20304\1083614715.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  analysis_df["het1yr_clean"] = analysis_df["het1yr"].replace({

In [20]:
for col in ["educ3", "ms2", "gor2"]:
    analysis_df[col] = (
        analysis_df[col]
        .astype("string")
        .str.strip()
        .str.lower()
    )

In [21]:
# convert pd.NA to np.nan first
analysis_df = analysis_df.replace({pd.NA: np.nan})

# clean text categories first
for col in ["educ3", "ms2", "gor2"]:
    analysis_df[col] = (
        analysis_df[col]
        .astype("object")
        .astype(str)
        .str.strip()
        .str.lower()
    )

# replace text missing labels
missing_labels = [
    "not answered",
    "not answered/don't know",
    "don't know",
    "nan",
    "<na>"
]

for col in ["educ3", "ms2", "gor2"]:
    analysis_df[col] = analysis_df[col].replace(missing_labels, np.nan)

In [22]:
# 9. Restrict to comparable age range
analysis_df = analysis_df[(analysis_df["dage"] >= 16) & (analysis_df["dage"] <= 44)]

In [23]:
# 10. Create readable labels
analysis_df["wave_label"] = analysis_df["survey_wave"].map({
    "1999_2001": "Natsal-2",
    "2010_2012": "Natsal-3"
})

In [24]:
# 11. fix gender capitalization
analysis_df["sex_clean"] = analysis_df["rsex"].str.lower().str.strip()

print(analysis_df["sex_clean"].value_counts(dropna=False))

sex_clean
female    12784
male       9228
Name: count, dtype: int64

In [25]:
# Create female dummy
analysis_df["female"] = analysis_df["sex_clean"].map({
    "male": 0,
    "female": 1
})

print(analysis_df["female"].value_counts(dropna=False))

female
1    12784
0     9228
Name: count, dtype: int64

In [26]:
# Create year dummy
analysis_df["year2010"] = analysis_df["survey_wave"].map({
    "1999_2001": 0,
    "2010_2012": 1
})

print(analysis_df["year2010"].value_counts(dropna=False))

year2010
0    12110
1     9902
Name: count, dtype: int64

In [27]:
# Check overdispersion
mean_y = analysis_df["het1yr_clean"].mean()
var_y = analysis_df["het1yr_clean"].var()

print("Mean:", mean_y)
print("Variance:", var_y)
print("Variance / Mean:", var_y / mean_y)

Mean: 1.4255991083039197
Variance: 6.023213495496682
Variance / Mean: 4.2250401676125415

In [28]:
model = smf.glm(
    formula="""
        het1yr_clean ~ C(year2010) * C(female)
        + dage + C(educ3) + C(ms2) + C(gor2)
    """,
    data=analysis_df,
    family=sm.families.NegativeBinomial(),
    freq_weights=analysis_df["total_wt"]
)

result = model.fit()
print(result.summary())

c:\Users\User\anaconda3\Lib\site-packages\statsmodels\genmod\families\family.py:1367: ValueWarning: Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.
  warnings.warn("Negative binomial dispersion parameter alpha not "

                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:           het1yr_clean   No. Observations:                21467
Model:                            GLM   Df Residuals:                 19723.10
Model Family:        NegativeBinomial   Df Model:                           17
Link Function:                    Log   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -31686.
Date:                Tue, 01 Sep 2026   Deviance:                       8997.0
Time:                        22:53:33   Pearson chi2:                 3.21e+04
No. Iterations:                     7   Pseudo R-squ. (CS):            0.02797
Covariance Type:            nonrobust
===============================================================================================================================================
                                                                                  coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------------------------------------------------------------
Intercept                                                                       0.4561      0.047      9.785      0.000       0.365       0.547
C(year2010)[T.1]                                                               -0.0256      0.038     -0.682      0.495      -0.099       0.048
C(female)[T.1]                                                                 -0.2227      0.025     -9.023      0.000      -0.271      -0.174
C(educ3)[T.foreign or other]                                                   -0.0710      0.093     -0.765      0.444      -0.253       0.111
C(educ3)[T.gcse, o-level or equivalent]                                         0.0478      0.026      1.862      0.063      -0.003       0.098
C(educ3)[T.higher education, <degree level but a-level/equiv]                   0.1634      0.036      4.593      0.000       0.094       0.233
C(educ3)[T.higher education, <degree level but a-level/equivalent]              0.0857      0.032      2.655      0.008       0.022       0.149
C(educ3)[T.none]                                                                0.0509      0.037      1.383      0.167      -0.021       0.123
C(ms2)[T.cohabitation (opposite sex & same sex)]                               -0.0029      0.029     -0.100      0.921      -0.059       0.053
C(ms2)[T.married & living with spouse]                                         -0.0710      0.026     -2.782      0.005      -0.121      -0.021
C(ms2)[T.married / civil partnership & living with spouse/partner]             -0.0711      0.046     -1.560      0.119      -0.160       0.018
C(ms2)[T.previously married (widowed, divorced, separated)]                     0.2953      0.046      6.472      0.000       0.206       0.385
C(ms2)[T.previously married / civil partner (widowed, divorced, separated)]     0.2260      0.080      2.811      0.005       0.068       0.384
C(ms2)[T.single and never been married]                                         0.2603      0.021     12.228      0.000       0.219       0.302
C(ms2)[T.single and never married or in a civil partnership]                    0.2387      0.044      5.436      0.000       0.153       0.325
C(gor2)[T.scotland]                                                             0.1016      0.033      3.122      0.002       0.038       0.165
C(gor2)[T.wales]                                                                0.0844      0.044      1.925      0.054      -0.002       0.170
C(year2010)[T.1]:C(female)[T.1]                                                 0.1100      0.039      2.851      0.004       0.034       0.186
dage                                                                           -0.0069      0.002     -4.552      0.000      -0.010      -0.004
===============================================================================================================================================